version: '3.8'

services:
  judify-app:
    build: 
      context: .
      dockerfile: dockerfile
    container_name: judify-app
    ports:
      - "3000:3000"
      - "5173:5173"
    volumes:
      - ./backend/database.db:/app/backend/database.db
      - ./backend/uploads:/app/backend/uploads
      - ./backend/notes:/app/backend/notes
      - ./backend/audio:/app/backend/audio
      - ./backend/.env:/app/backend/.env
    restart: unless-stopped
    environment:
      - NODE_ENV=development
